/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package serveur;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.LayoutManager;
import java.awt.TextField;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Timer;

import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

/**
 *
 * @author Andreas
 */
public class Fenetre extends javax.swing.JFrame {
	private Log log;

    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
		Timer timer = new Timer();
        this.setVisible(true);
    }
    
    public void setLog(Log alog){
    	log=alog;
    }
    
    public void majlog(){
        FileReader fr;
        File file = new File("log.txt");
        String str ="";
    	//Cr�ation de l'objet de lecture
        try {
			fr = new FileReader(file);
	        str = "";
	        int i = 0;
	        //Lecture des donn�es
	        while((i = fr.read()) != -1){
	          str += (char)i;
	        }
	        jTextAreaLog.setText(str);
	        jTextAreaLog.setCaretPosition(jTextAreaLog.getDocument().getLength());
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jPanelReseau = new javax.swing.JPanel();
        jPanelAccueil = new javax.swing.JPanel();
        jPanelAccueil.setLayout(new  BoxLayout(jPanelAccueil, BoxLayout.Y_AXIS));
        jButton1 = new JButton();
        String ipLocale = "";
        String ipPublique = "";
        try {
			ipLocale = InetAddress.getLocalHost().getHostAddress().toString();
		} catch (UnknownHostException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        try {
			ipPublique=IP.findIP("http://whatismyipaddress.com/", "<!-- do not script -->", "");
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        jTextAreaIpLocale = new JTextArea(ipLocale);
        jTextAreaIpPublique=new JTextArea(ipPublique);
        jLabelIpLocal=new JLabel("Ip locale du serveur : ");
        jLabelIpPublique=new JLabel("Ip publique  du serveur : ");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane1.setSize(100, 2000);
        jScrollPane1.setViewportView(jTextAreaLog);

        jTabbedPane1.addTab("GHome", jPanelAccueil);
        jTabbedPane1.addTab("Reseau", jPanelReseau);

        jPanelAccueil.add(jLabelIpLocal);
        jPanelAccueil.add(jTextAreaIpLocale);
        jPanelAccueil.add(jLabelIpPublique);
        jPanelAccueil.add(jTextAreaIpPublique);
        jPanelAccueil.add(jButton1);
        jPanelAccueil.add(jScrollPane1);
        

        jButton1.setText("Demarrer serveur");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ConnexionClient conn = new ConnexionClient(log, this);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanelReseau;
    private javax.swing.JPanel jPanelAccueil;
    private javax.swing.JLabel jLabelIpLocal;
    private javax.swing.JLabel jLabelIpPublique;
    private javax.swing.JTextArea jTextAreaIpLocale;
    private javax.swing.JTextArea jTextAreaIpPublique;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaLog;
    // End of variables declaration//GEN-END:variables
}
